# Generated by Django 5.2.1 on 2025-05-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160, null=True)),
                ('descricao', models.TextField()),
                ('prioridade', models.CharField(choices=[('B', 'Baixa'), ('M', 'Media'), ('A', 'Alta')])),
                ('prazo', models.DateField()),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('EA', 'Em Andamento'), ('C', 'Concluída')])),
            ],
            options={
                'verbose_name': '',
                'ordering': ['id'],
            },
        ),
    ]
