# Generated by Django 5.2.1 on 2025-05-10 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='prazo',
            field=models.DateField(null=True, verbose_name='Prazo'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='prioridade',
            field=models.CharField(choices=[('B', 'Baixa'), ('M', 'Media'), ('A', 'Alta')], verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('EA', 'Em Andamento'), ('C', 'Concluída')], default='P', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='titulo',
            field=models.CharField(max_length=160, null=True, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
