# Generated by Django 5.2.1 on 2025-05-08 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('EA', 'Em Andamento'), ('C', 'Concluída')], default='P'),
        ),
    ]
